{ wasisabi, ... }:

# Your machine-specific config: identity, hardware file, and the wasisabi
# layers on top. Everything wasisabi sets is a mkDefault, so anything you
# write here wins.

{
  imports = [
    # Generated by the installer / nixos-generate-config:
    ./hardware-configuration.nix

    # Example: hardware quirks for a ThinkPad T14s Gen 3 AMD
    # (uncomment the nixos-hardware module in flake.nix too):
    # <nixos-hardware/lenovo/thinkpad/t14s/amd>
  ];

  networking.hostName = "CHANGEME_HOSTNAME";

  users.users.CHANGEME_USERNAME = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
    initialPassword = "change-me";
  };

  # ── wasisabi system layer ──
  wasisabi.enable = true;
  # wasisabi.zram.enable = true;
  # wasisabi.cellular.enable = true;   # WWAN/LTE modems

  # ── wasisabi home layer, for your user ──
  home-manager.users.CHANGEME_USERNAME = {
    imports = [ wasisabi.homeModules.wasisabi ];
    wasisabi.enable = true;
    # Overriding the opinionated defaults is the whole point:
    # wasisabi.browser = "librewolf";
    # wasisabi.editor = "helix";
    # wasisabi.apps.office = true;
    # wasisabi.apps.syncthing = true;
  };
}