# modules/anonctl-units.nix
#
# THE TWO SHARED anonctl UNIT FILES, DECLARED. The third half of "what anonctl
# needs from a declarative host", after modules/anon-accounts.nix (the passwd
# slots) and modules/anon-dns.nix (the resolver): the `anonctl-shim@.service`
# template and the `anonctl-nftables.service` early-boot loader, built from text
# anonctl itself emits and installed into the system closure.
#
# WHY. Until now those two files were written by `anonctl add` into
# /usr/local/lib/systemd/system and nothing in this repo knew they existed: no
# rebuild reproduced them, no rollback undid them, and a REBIRTH restored the
# declared accounts (modules/anon-accounts.nix) and the declared binary
# (packages/anonctl.nix) while leaving those accounts with nothing that installs
# their forcing at boot. That is the same class of drift the binary already had
# and this fleet already fixed once: telemaque ran a hand-installed anonctl
# v0.3.1 for weeks while this repo's comments assumed v0.5.0 behaviour. The
# units were the remainder.
#
# It bites in two places that are not hypothetical:
#
#   - A reborn box comes back with accounts and no units, i.e. an account that
#     still exists and still looks anonymised while nothing loads its jail.
#   - modules/wherever-anon-reconcile.nix is ordered `After=anonctl-nftables.service`
#     and gates every provisioning decision on `anonctl probe`. With the loader
#     missing, the probe reports table-missing and reconcile retracts every
#     route: fail-closed and loud, but caused by state nothing declared.
#
# WHAT THIS DOES NOT DECLARE, and must never. The division is anonctl's own
# ADR-0012 and it is not a style preference:
#
#   declared here          | anonctl's, always
#   -----------------------|-------------------------------------------------
#   anonctl-shim@.service  | multi-user.target.wants/anonctl-shim@<account>.service
#   anonctl-nftables.service | sysinit.target.wants/anonctl-nftables.service
#   the host-owned marker  | /etc/anonctl/shim/<account>.env, /etc/anonctl/nftables/*.nft
#                          | the ledger, the live nft rules
#
# The right-hand column is per-account, and the ENABLEMENT SYMLINK is the point:
# its NAME says which slot is in use. Declaring it would publish to this repo and
# its git history which slots are live, when each became live and in what order,
# which is exactly the timeline the declared pool exists to withhold (the
# declared-versus-observed rule; see the genericity claims in flake.nix). The two
# files above are account-agnostic by construction: the shim is a `%i` template
# whose every per-account value arrives through an EnvironmentFile, and the
# loader globs a directory. That is what makes them declarable at all.
#
# SO DO NOT SET `wantedBy` ON EITHER UNIT. Enablement stays anonctl's, and it
# keeps working: it writes its symlinks into its own unit dir, where they now
# point at a path that holds no file, and systemd resolves a `.wants` entry by
# unit NAME rather than by target. Upstream measured this on systemd 260 with the
# declaration in the higher-precedence directory and the dangling symlink in the
# lower one: Wants= present, LoadState=loaded, FragmentPath the declared file,
# and starting the target starts the instance.
#
# THE TEXT IS NOT MAINTAINED HERE, which is the whole point of doing this after
# anonctl 0.9.0 rather than before it. A host that declared these units from text
# it wrote by hand would take on a drift hazard strictly worse than the undeclared
# state it was fixing: two definitions of one unit, /etc/systemd/system silently
# outranking /usr/local/lib/systemd/system, and anonctl's copy sitting next to it
# looking authoritative. Instead the package ships `share/anonctl/units/*.in`,
# GENERATED by the same function `anonctl add` installs through (upstream holds
# the two byte-identical by test), and this module only substitutes the
# host-varying paths into it.
#
# THREE VALUES ARE NOT FREE, and getting one wrong is the worst failure available
# on this box, so they are pinned here, asserted by
# `wherever-anon-is-jailed-and-carries-no-observed-state` in flake.nix, re-checked
# by the `anonctl-units-are-the-emitters-own-text` check, refused by `anonctl add`
# and re-checked by every `anonctl verify`:
#
#   - `envDir` must be where anonctl writes the per-account EnvironmentFiles.
#   - `rulesDir` must be where anonctl writes the persisted .nft files.
#   - every binary path must be ABSOLUTE (a unit inherits no useful $PATH, so
#     `nft` is exit 127 at boot).
#
# A loader that globs a directory anonctl does not write to, or that cannot run
# `nft` at all, loads NOTHING at boot: no forcing, and no standing baseline
# default-deny, so the account egresses with this box's real IP. It is SILENT,
# because the live rules stay correct while the machine is up and the loader is
# enabled-but-not-started, so the mistake is first evaluated at the boot it
# breaks.
#
# A /nix/store PATH IN ExecStart IS CORRECT HERE, AND ONLY HERE. The rule in
# anonctl's OWN work/notes/observations/resolved-unit-binaries-can-bake-a-nix-store-path-from-path.md
# (that note lives in the anonctl repo, not this one)
# is about a path anonctl RESOLVES at install time: nothing tracks that reference,
# so a later GC can delete the binary and the unit dies weeks later with nothing
# having changed. A path this module DECLARES is the opposite case: the unit text
# is itself a store file, Nix scans it for references, so the binary is a real
# edge from the system closure, cannot be collected while the generation naming
# it exists, and rolls back with everything else. Upstream pinned that by test
# (`verify`'s volatile-path check names /tmp, /var/tmp, /dev/shm and /run/user,
# and deliberately not /nix/store).
#
# THE DUTY THIS TAKES ON. In host-owned mode anonctl can no longer REPAIR these
# units: `update`'s re-bake exists because binaries move, and that is now this
# module's job. anonctl reports the condition at `add`, at `update` and at every
# `verify`, and will not write the fix. Since every path here comes from the same
# pins the fleet already declares, a bump moves them together and a rollback
# takes them back together, which is what makes that duty cheap rather than a new
# thing to remember.
#
# ONE-TIME OPERATOR STEP ON A BOX THAT ALREADY RAN `add`. anonctl's own copies
# stay in /usr/local/lib/systemd/system and are now SHADOWED by the declaration
# (the /etc/systemd/system copies win). anonctl reports the shadowing and refuses
# to delete the winner, deliberately, because on a declarative host the winner is
# very likely the host's own file. Remove the losers by hand, once:
#
#   sudo rm /usr/local/lib/systemd/system/anonctl-nftables.service \
#           '/usr/local/lib/systemd/system/anonctl-shim@.service'
#   sudo systemctl daemon-reload
#
# The `.wants` directories next to them must STAY: those are the enablement, they
# are anonctl's, and removing them unenables every account's shim.
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.wasisabi.services.anonctlUnits;

  # THE SUBSTITUTIONS, AS DATA, so exactly one attrset feeds the derivation below
  # and the checks in flake.nix. A claim reads what the build consumed rather than
  # a restatement of it, which is why `substitutions` is a read-only option rather
  # than a local.
  subs = {
    "anonctl-nftables.service" = {
      "@nft@" = cfg.nft;
      "@rulesDir@" = cfg.rulesDir;
    };
    "anonctl-shim@.service" = {
      "@setpriv@" = cfg.setpriv;
      "@shim@" = cfg.shim;
      "@envDir@" = cfg.envDir;
    };
  };

  # Keyed by the unit's OWN FILE NAME, so the attrset above is the only place a
  # unit name is written: the file installed, the placeholders substituted into it
  # and the name the checks assert over cannot disagree, because there is one
  # source for all three. modules/wherever-anon-reconcile.nix orders itself
  # `After=anonctl-nftables.service`, and that string is worth nothing unless a
  # unit by that name is actually declared here.
  installUnit = unit: ''
    substitute "${cfg.package}/share/anonctl/units/${unit}.in" \
      "$out/lib/systemd/system/${unit}" \
      ${
      lib.concatStringsSep " "
      (lib.mapAttrsToList (token: value: "--replace-fail '${token}' '${value}'")
        subs.${unit})
    }
  '';

  # `--replace-fail` turns a token the package renamed into a BUILD error rather
  # than a unit that ships with `@rulesDir@` still in it. The explicit sweep after
  # it covers the other direction: a placeholder this module never knew about
  # (upstream adding a sixth one in some later release) would substitute cleanly
  # and survive into the unit, where it fails at the next boot instead.
  unitsPackage =
    pkgs.runCommand "anonctl-units-${cfg.package.version}" {
      meta.description = "anonctl's two shared systemd units, substituted for this host";
    } ''
      mkdir -p $out/lib/systemd/system

      ${lib.concatStringsSep "\n" (map installUnit (lib.attrNames subs))}

      if grep -n '@[a-zA-Z][a-zA-Z]*@' $out/lib/systemd/system/*; then
        echo "anonctl-units: a placeholder survived substitution (see above)." >&2
        echo "The unit would fail at the next boot, not here. Refusing to build." >&2
        exit 1
      fi
    '';
in {
  options.wasisabi.services.anonctlUnits = {
    enable = lib.mkEnableOption ''
      anonctl's two SHARED systemd units, declared by this host from the text the
      packaged anonctl emits, plus the /etc/anonctl/units.host-owned marker that
      tells anonctl to stop writing its own copy.

      The per-account enablement symlinks, the env files, the rule files, the
      ledger and the live nft rules stay anonctl's in every mode. Needs anonctl
      0.9.0 or newer, which is where the marker means anything at all
    '';

    package = lib.mkOption {
      type = lib.types.package;
      description = ''
        The anonctl package whose emitted unit text is declared, and whose
        `anonctl-shim` the shim unit runs. Must be the SAME derivation the host
        puts on PATH: the units and the CLI that validates them are one release,
        and a box running one build while its units name another is precisely the
        drift this module exists to end.
      '';
    };

    setpriv = lib.mkOption {
      type = lib.types.str;
      default = "${pkgs.util-linux}/bin/setpriv";
      defaultText = lib.literalExpression "\"\${pkgs.util-linux}/bin/setpriv\"";
      description = ''
        Absolute path to `setpriv`, which drops the shim to the account's
        dedicated shim uid. That uid drop IS the per-account security boundary,
        so this is not a convenience path.
      '';
    };

    nft = lib.mkOption {
      type = lib.types.str;
      default = "${pkgs.nftables}/bin/nft";
      defaultText = lib.literalExpression "\"\${pkgs.nftables}/bin/nft\"";
      description = ''
        Absolute path to `nft`, which the early-boot loader runs over anonctl's
        rule files. A path that does not resolve at boot is exit 127 and loads
        nothing at all, which is fail-OPEN and silent.
      '';
    };

    shim = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.package}/bin/anonctl-shim";
      defaultText = lib.literalExpression "\"\${package}/bin/anonctl-shim\"";
      description = ''
        Absolute path to the per-account data-path shim, taken from the same
        package as the CLI so the two cannot be different releases.
      '';
    };

    envDir = lib.mkOption {
      type = lib.types.str;
      default = "/etc/anonctl/shim";
      description = ''
        Where anonctl writes each account's EnvironmentFile. Pinned to anonctl's
        own directory, not configurable taste: the shim template reads
        `<envDir>/%i.env`, and a unit pointed one directory sideways starts an
        instance with no endpoint at all. `anonctl add` refuses when this
        disagrees with anonctl, and `anonctl verify` re-checks it.
      '';
    };

    rulesDir = lib.mkOption {
      type = lib.types.str;
      default = "/etc/anonctl/nftables";
      description = ''
        Where anonctl persists the per-account forcing AND the standing baseline
        default-deny. The loader globs this directory at boot, so a value anonctl
        does not write to loads nothing: no forcing and no baseline, i.e. free
        egress with this box's real IP, silently, from the next boot onwards.
      '';
    };

    substitutions = lib.mkOption {
      type = lib.types.attrsOf (lib.types.attrsOf lib.types.str);
      readOnly = true;
      internal = true;
      default = subs;
      description = ''
        What was substituted into each unit, exposed so the flake's checks can
        assert over the values the build actually consumed rather than over a
        second copy of them.
      '';
    };

    unitsPackage = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      internal = true;
      default = unitsPackage;
      description = ''
        The derivation carrying the two substituted units, exposed so the flake's
        `anonctl-units-are-the-emitters-own-text` check can diff the very files
        this host installs against what `anonctl units print` produces for the
        same flags.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        # The floor is not stylistic. Under 0.8.1 the marker below is an
        # unremarkable file: `add` and `update` would each write their own copy of
        # both units into /usr/local/lib/systemd/system, next to this host's
        # declaration, and systemd would pick the declaration without saying so
        # while anonctl reported success over the copy it thought it had
        # installed.
        assertion = lib.versionAtLeast cfg.package.version "0.9.0";
        message = ''
          wasisabi.services.anonctlUnits needs anonctl 0.9.0 or newer (the release that exports
          the unit text and honours /etc/anonctl/units.host-owned); this host
          declares ${cfg.package.version}.
        '';
      }
    ];

    # NOT `systemd.units.<name>.text`, deliberately. That shape wants
    # `builtins.readFile` on a path inside a package, which is
    # import-from-derivation: it works under nixos-rebuild (IFD is on by default)
    # and fails under restricted evaluation, which is how `nix flake check` runs
    # here. `systemd.packages` never reads the text at eval time, and NixOS links
    # $out/lib/systemd/system into /etc/systemd/system while deliberately SKIPPING
    # .wants directories, so this shape cannot smuggle in an enablement even by
    # accident.
    systemd.packages = [cfg.unitsPackage];

    # HANDING OWNERSHIP OVER. The presence of the file is the entire signal;
    # anonctl ignores the content, so it is used to tell the next person which
    # module to look in. With it in place `add` and `update` write neither unit
    # file, `rm` never deletes them (including the last-account teardown that
    # removes them on an ordinary host), and the pre-0.4 sweep of
    # /etc/systemd/system is skipped, because that is where this module declares
    # them and anonctl cannot tell a declaration from someone's leftovers by path.
    #
    # It also makes `add` REFUSE up front unless the declaration is usable: both
    # units in systemd's search path, no surviving placeholder, every binary they
    # name absolute and existing, and the directories agreeing with anonctl's own.
    # The marker WITHOUT the units would otherwise be the worst outcome available,
    # which is why the two are declared together here and cannot be enabled apart.
    environment.etc."anonctl/units.host-owned".text = ''
      The two shared anonctl unit files on this box are DECLARED by its NixOS
      configuration, in modules/anonctl-units.nix, and installed through
      systemd.packages into /etc/systemd/system. anonctl must not write, rewrite
      or delete them.

      Still anonctl's here, and not declared anywhere: the per-account enablement
      symlinks under /usr/local/lib/systemd/system/*.wants/, the env files under
      ${cfg.envDir}, the rule files under ${cfg.rulesDir}, the ledger, and the
      live nftables rules. The symlink names say which slots are in use, which is
      why they stay out of the configuration repository.
    '';
  };
}
