{
  lib,
  runCommand,
  grub2_efi,
  imagemagick,
  inter,
  fraunces,
  wasisabi-artwork,
}:

# The GRUB theme of the ISOs' boot menu (isoImage.grubTheme). Laid out like
# the website's first screen: the wallpaper, darkened on the left, and the
# menu set in that dark half.
#
# Everything is DERIVED at build time: the background from the wallpaper (so a
# new wallpaper is a new menu), the .pf2 fonts from the same Fraunces and Inter
# the website uses. grub-mkfont's -n pins each font's family name, which is
# what theme.txt refers to, rather than whatever the TTF calls itself.
let
  p = import ../../theme/palettes.nix;
  c = p.sumi;
  wallpaper = "${wasisabi-artwork}/share/backgrounds/wasisabi/enso.jpg";
in
runCommand "wasisabi-grub-theme"
  {
    nativeBuildInputs = [ grub2_efi imagemagick ];
    meta.license = lib.licenses.cc0;
  }
  ''
    mkdir -p $out

    # 1920x1080, the mode the ISO's grub.cfg asks for first after 1920x1200;
    # GRUB stretches the image to whatever mode it gets.
    #
    # The wallpaper's brush stroke is on its right, so it stays there, and a
    # left-to-right ink gradient makes a quiet field for the menu, as on the
    # website.
    # A second gradient darkens the bottom, where the timeout and the key
    # hints sit over the print's speckled paper.
    magick ${wallpaper} -resize 1920x1080^ -gravity east -extent 1920x1080 \
      \( -size 1080x1920 gradient:'#${c.base}f2-#${c.base}00' -rotate 90 \) \
      -gravity west -compose over -composite \
      \( -size 1920x360 gradient:'#${c.base}00-#${c.base}e6' \) \
      -gravity south -compose over -composite \
      -strip -depth 8 PNG24:$out/background.png

    # The selected entry: a faint paper wash with a vermilion edge, the seal
    # colour, marking the one thing this screen asks you to choose.
    #
    # PNG32: GRUB's PNG reader only takes 8-bit RGB(A), and ImageMagick would
    # otherwise save a one-colour image as 1-bit, which GRUB silently skips.
    magick -size 1x1 xc:'#${c.bright}1f' PNG32:$out/select_c.png
    # The left slice is the edge plus a strip of the wash: GRUB starts the
    # entry's text right after it, so its width is the text's breathing room.
    magick -size 4x1 xc:'#${c.urgent}' -size 14x1 xc:'#${c.bright}1f' +append PNG32:$out/select_w.png
    for s in n s nw ne sw se e; do magick -size 1x1 xc:'#00000000' PNG32:$out/select_$s.png; done

    grub-mkfont -n WasiSerif -s 64 -o $out/serif-64.pf2 \
      ${fraunces}/share/fonts/truetype/Fraunces72ptSoft-Light.ttf
    grub-mkfont -n WasiSans -s 24 -o $out/sans-24.pf2 ${inter}/share/fonts/truetype/InterVariable.ttf
    grub-mkfont -n WasiSans -s 18 -o $out/sans-18.pf2 ${inter}/share/fonts/truetype/InterVariable.ttf

    cat > $out/theme.txt <<'EOF'
    # wasisabi. Generated by pkgs/wasisabi-grub-theme; edit that, not this.
    title-text: ""
    desktop-image: "background.png"
    desktop-color: "#${c.base}"
    terminal-font: "WasiSans Regular 18"

    + label {
      left = 8%
      top = 22%
      width = 50%
      height = 80
      text = "wasisabi"
      font = "WasiSerif Regular 64"
      color = "#${c.bright}"
    }

    + label {
      left = 8%
      top = 22%+96
      width = 50%
      height = 30
      text = "A desktop that stays yours."
      font = "WasiSans Regular 24"
      color = "#${c.subtext}"
    }

    + boot_menu {
      left = 8%
      top = 42%
      width = 44%
      height = 40%
      item_font = "WasiSans Regular 24"
      item_color = "#${c.subtext}"
      selected_item_font = "WasiSans Regular 24"
      selected_item_color = "#${c.bright}"
      selected_item_pixmap_style = "select_*.png"
      item_height = 48
      item_padding = 18
      item_spacing = 8
      icon_width = 0
      icon_height = 0
      item_icon_space = 0
      scrollbar = false
    }

    + label {
      id = "__timeout__"
      left = 8%
      top = 88%
      width = 60%
      height = 24
      text = "Starting in %d s"
      font = "WasiSans Regular 18"
      color = "#${c.subtext}"
    }

    + label {
      left = 8%
      top = 92%
      width = 84%
      height = 24
      text = "Enter to start     Arrows to choose     E to edit     T for text mode"
      font = "WasiSans Regular 18"
      color = "#${c.subtext}"
    }
    EOF
  ''
